name: Keep Render and Streamlit Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Ping Backend and Frontend
        run: |
          # Replace these URLs with your actual Render backend and Streamlit frontend URLs
          curl -s -m 10 "https://movie-recommendation-ocuk.onrender.com/" > /dev/null
          curl -s -m 10 "https://movie-recommendation-rikki.streamlit.app/" > /dev/null
          echo "Pinged both services successfully!"

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
